### PR TITLE
fix: hardlink social redirects, fixes #108

### LINKED ISSUE #108: bug: revanced.app/github buggin out
https://github.com/revanced/revanced-website/assets/31113245/daf44590-8576-475c-ab37-c6039a466d4f

### PR DESCRIPTION
**Pull request by PickleNik**

### CODE REVIEW

File: src/layout/Hero/SocialHost.svelte [hunk 1]
```diff
@@ -3,10 +3,10 @@
 </script>
 
 <div class="social-host">
```
Comment (oSumAtrIX) [inline src/layout/Hero/SocialHost.svelte:5]:
```suggestion
<!-- TODO: Use API social links -->
<div class="social-host">
```

**Review by oSumAtrIX — APPROVED** [review]
